[build]
  publish = "build_production"
  command = "npm run production"

[build.environment]
  PHP_VERSION = "7.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; font-src 'self' data:; report-uri https://hmazter.report-uri.com/r/d/csp/enforce"
    Feature-Policy = ""