[build.environment]
  PHP_VERSION = 7.2

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy-Report-Only = "script-src 'self'; style-src 'self' https://fonts.googleapis.com https://use.fontawesome.com; font-src https://use.fontawesome.com https://fonts.gstatic.com; report-uri https://hmazter.report-uri.com/r/d/csp/reportOnly"